#ifndef CLIPDATA_CONSTANTS_H
#define CLIPDATA_CONSTANTS_H

enum ClipdataAffectingAction {
    CAA_NONE,
    CAA_REMOVE_SOLID,
    CAA_MAKE_SOLID,
    CAA_MAKE_SOLID_STOP_ENEMY,
    CAA_4,
    CAA_ENEMY_PROJECTILE,
    CAA_BEAM,
    CAA_BOMB,
    CAA_MISSILE,
    CAA_POWER_BOMB,
    CAA_SPEED_BOOST,
    CAA_SPEED_BOOST_GROUND,
    CAA_SCREW_ATTACK,
    CAA_BOMB_CHAIN,

    CAA_END,
};

#define COLLISION_AIR 0
#define COLLISION_LEFT_SLIGHT_FLOOR_SLOPE 2
#define COLLISION_RIGHT_SLIGHT_FLOOR_SLOPE 3
#define COLLISION_LEFT_STEEP_FLOOR_SLOPE 4
#define COLLISION_RIGHT_STEEP_FLOOR_SLOPE 5
#define COLLISION_PASS_THROUGH_BOTTOM 16
#define COLLISION_SOLID 17
#define COLLISION_FLAGS_UNKNOWN (COLLISION_PASS_THROUGH_BOTTOM | 0x20 | 0x40 | 0x80)

#define CLIPDATA_TYPE_AIR 0
#define CLIPDATA_TYPE_SOLID 1
#define CLIPDATA_TYPE_LEFT_STEEP_FLOOR_SLOPE 2
#define CLIPDATA_TYPE_RIGHT_STEEP_FLOOR_SLOPE 3
#define CLIPDATA_TYPE_LEFT_UPPER_SLIGHT_FLOOR_SLOPE 4
#define CLIPDATA_TYPE_LEFT_LOWER_SLIGHT_FLOOR_SLOPE 5
#define CLIPDATA_TYPE_RIGHT_LOWER_SLIGHT_FLOOR_SLOPE 6
#define CLIPDATA_TYPE_RIGHT_UPPER_SLIGHT_FLOOR_SLOPE 7
#define CLIPDATA_TYPE_ENEMY_ONLY 8
#define CLIPDATA_TYPE_STOP_ENEMY 9
#define CLIPDATA_TYPE_TANK 10
#define CLIPDATA_TYPE_DOOR 11
#define CLIPDATA_TYPE_PASS_THROUGH_BOTTOM 12
#define CLIPDATA_TYPE_SOLID_FLAG 0x1000000

#endif /* CLIPDATA_CONSTANTS_H */
