#ifndef CLIPDATA_CONSTANTS_H
#define CLIPDATA_CONSTANTS_H

enum ClipdataAffectingAction {
    CAA_NONE,
    CAA_REMOVE_SOLID,
    CAA_MAKE_SOLID,
    CAA_MAKE_SOLID_STOP_ENEMY,
    CAA_4,
    CAA_ENEMY_PROJECTILE,
    CAA_BEAM,
    CAA_BOMB,
    CAA_MISSILE,
    CAA_POWER_BOMB,
    CAA_SPEED_BOOST,
    CAA_SPEED_BOOST_GROUND,
    CAA_SCREW_ATTACK,
    CAA_BOMB_CHAIN,

    CAA_END,
};

enum CollisionActor {
    COLLISION_ACTOR_SAMUS,
    COLLISION_ACTOR_NON_SPRITE,
    COLLISION_ACTOR_SPRITE,
};

enum GroudEffect {
    GROUND_EFFECT_NONE,
    GROUND_EFFECT_WET_GROUND,
    GROUND_EFFECT_DUSTY_GROUND,
    GROUND_EFFECT_VERY_DUSTY_GROUND,
    GROUND_EFFECT_4,
    GROUND_EFFECT_BUBBLY_GROUND,

    GROUND_EFFECT_END,
};

enum Elevator {
    ELEVATOR_MAIN_DECK_TO_OPERATIONS_DECK,
    ELEVATOR_MAIN_DECK_TO_LOBBY,
    ELEVATOR_MAIN_DECK_TO_SECTOR_1,
    ELEVATOR_MAIN_DECK_TO_SECTOR_2,
    ELEVATOR_MAIN_DECK_TO_SECTOR_3,
    ELEVATOR_MAIN_DECK_TO_SECTOR_4,
    ELEVATOR_MAIN_DECK_TO_SECTOR_5,
    ELEVATOR_MAIN_DECK_TO_SECTOR_6,
    ELEVATOR_MAIN_DECK_TO_LOBBY_POWER_OUTAGE,
    ELEVATOR_MAIN_DECK_TO_HABITATIONS_DECK,
    ELEVATOR_RESTRICTED_ZONE_TO_SECTOR_1,

    ELEVATOR_END
};

#define COLLISION_AIR 0
#define COLLISION_LEFT_SLIGHT_FLOOR_SLOPE 2
#define COLLISION_RIGHT_SLIGHT_FLOOR_SLOPE 3
#define COLLISION_LEFT_STEEP_FLOOR_SLOPE 4
#define COLLISION_RIGHT_STEEP_FLOOR_SLOPE 5
#define COLLISION_PASS_THROUGH_BOTTOM 0x10
#define COLLISION_SOLID 0x11
#define COLLISION_FLAGS_UNKNOWN_F (0x1 | COLLISION_LEFT_SLIGHT_FLOOR_SLOPE | COLLISION_LEFT_STEEP_FLOOR_SLOPE | 0x8)
#define COLLISION_FLAGS_UNKNOWN_F0 (COLLISION_PASS_THROUGH_BOTTOM | 0x20 | 0x40 | 0x80)

enum ClipdataType {
    CLIPDATA_TYPE_AIR,
    CLIPDATA_TYPE_SOLID,
    CLIPDATA_TYPE_LEFT_STEEP_FLOOR_SLOPE,
    CLIPDATA_TYPE_RIGHT_STEEP_FLOOR_SLOPE,
    CLIPDATA_TYPE_LEFT_UPPER_SLIGHT_FLOOR_SLOPE,
    CLIPDATA_TYPE_LEFT_LOWER_SLIGHT_FLOOR_SLOPE,
    CLIPDATA_TYPE_RIGHT_LOWER_SLIGHT_FLOOR_SLOPE,
    CLIPDATA_TYPE_RIGHT_UPPER_SLIGHT_FLOOR_SLOPE,
    CLIPDATA_TYPE_ENEMY_ONLY,
    CLIPDATA_TYPE_STOP_ENEMY,
    CLIPDATA_TYPE_TANK,
    CLIPDATA_TYPE_DOOR,
    CLIPDATA_TYPE_PASS_THROUGH_BOTTOM,

    CLIPDATA_TYPE_END
};

#define CLIPDATA_TYPE_SOLID_FLAG 0x1000000

enum ClipdataMovement {
    CLIPDATA_MOVEMENT_NONE,
    CLIPDATA_MOVEMENT_ELEVATOR_DOWN,
    CLIPDATA_MOVEMENT_ELEVATOR_UP,
    CLIPDATA_MOVEMENT_WALL_LADDER,
    CLIPDATA_MOVEMENT_PREVENTS_CLIMBING_INTO_FROM_LADDER,
    CLIPDATA_MOVEMENT_CEILING_LADDER,
    CLIPDATA_MOVEMENT_BEHAVIOR_10,
    CLIPDATA_MOVEMENT_BEHAVIOR_11,
    CLIPDATA_MOVEMENT_BEHAVIOR_96,

    CLIPDATA_MOVEMENT_END,
};

enum Hazard {
    HAZARD_NONE,
    HAZARD_WATER,
    HAZARD_LAVA,
    HAZARD_ACID,
    HAZARD_HEAT,
    HAZARD_COLD_KNOCKBACK,
    HAZARD_COLD,

    HAZARD_END,
};

enum ClipdataBehavior {
    CLIP_BEHAVIOR_NONE,
    CLIP_BEHAVIOR_ELEVATOR_DOWN,
    CLIP_BEHAVIOR_ELEVATOR_UP,
    CLIP_BEHAVIOR_DOOR_TRANSITION,
    CLIP_BEHAVIOR_VERTICAL_UP_TRANSITION,
    CLIP_BEHAVIOR_VERTICAL_DOWN_TRANSITION,
    CLIP_BEHAVIOR_6,
    CLIP_BEHAVIOR_PREVENTS_CLIMBING_INTO_FROM_LADDER,
    CLIP_BEHAVIOR_WALL_LADDER,
    CLIP_BEHAVIOR_CEILING_LADDER,

    CLIP_BEHAVIOR_10,
    CLIP_BEHAVIOR_11,
    CLIP_BEHAVIOR_12,
    CLIP_BEHAVIOR_13,
    CLIP_BEHAVIOR_14,
    CLIP_BEHAVIOR_15,

    CLIP_BEHAVIOR_SHOT_BLOCK_NEVER_REFORM,
    CLIP_BEHAVIOR_TOP_LEFT_SHOT_BLOCK_NEVER_REFORM,
    CLIP_BEHAVIOR_TOP_RIGHT_SHOT_BLOCK_NEVER_REFORM,
    CLIP_BEHAVIOR_BOTTOM_LEFT_SHOT_BLOCK_NEVER_REFORM,
    CLIP_BEHAVIOR_BOTTOM_RIGHT_SHOT_BLOCK_NEVER_REFORM,
    CLIP_BEHAVIOR_SHOT_BLOCK_REFORM,
    CLIP_BEHAVIOR_MISSILE_BLOCK_NEVER_REFORM,
    CLIP_BEHAVIOR_BOMB_BLOCK_NEVER_REFORM,
    CLIP_BEHAVIOR_BOMB_BLOCK_REFORM,
    CLIP_BEHAVIOR_POWER_BOMB_BLOCK_NEVER_REFORM,
    CLIP_BEHAVIOR_MISSILE_BLOCK_NO_REFORM,
    CLIP_BEHAVIOR_SHOT_BLOCK_NO_REFORM,
    CLIP_BEHAVIOR_TOP_LEFT_SHOT_BLOCK_NO_REFORM,
    CLIP_BEHAVIOR_TOP_RIGHT_SHOT_BLOCK_NO_REFORM,
    CLIP_BEHAVIOR_BOTTOM_LEFT_SHOT_BLOCK_NO_REFORM,
    CLIP_BEHAVIOR_BOTTOM_RIGHT_SHOT_BLOCK_NO_REFORM,
    CLIP_BEHAVIOR_SPEED_BOOST_BLOCK_NO_REFORM,
    CLIP_BEHAVIOR_SPEED_BOOST_BLOCK_REFORM,
    CLIP_BEHAVIOR_SCREW_ATTACK_BLOCK_NO_REFORM,
    CLIP_BEHAVIOR_CRUMBLE_BLOCK,

    CLIP_BEHAVIOR_ENERGY_TANK,
    CLIP_BEHAVIOR_MISSILE_TANK,
    CLIP_BEHAVIOR_POWER_BOMB_TANK,
    CLIP_BEHAVIOR_HIDDEN_ENERGY_TANK,
    CLIP_BEHAVIOR_HIDDEN_MISSILE_TANK,
    CLIP_BEHAVIOR_HIDDEN_POWER_BOMB_TANK,
    CLIP_BEHAVIOR_UNDERWATER_ENERGY_TANK,
    CLIP_BEHAVIOR_UNDERWATER_MISSILE_TANK,
    CLIP_BEHAVIOR_UNDERWATER_POWER_BOMB_TANK,

    CLIP_BEHAVIOR_VERTICAL_BOMB_CHAIN_1,
    CLIP_BEHAVIOR_VERTICAL_BOMB_CHAIN_2,
    CLIP_BEHAVIOR_VERTICAL_BOMB_CHAIN_3,
    CLIP_BEHAVIOR_VERTICAL_BOMB_CHAIN_4,
    CLIP_BEHAVIOR_HORIZONTAL_BOMB_CHAIN_1,
    CLIP_BEHAVIOR_HORIZONTAL_BOMB_CHAIN_2,
    CLIP_BEHAVIOR_HORIZONTAL_BOMB_CHAIN_3,
    CLIP_BEHAVIOR_HORIZONTAL_BOMB_CHAIN_4,

    CLIP_BEHAVIOR_53,
    CLIP_BEHAVIOR_54,
    CLIP_BEHAVIOR_55,
    CLIP_BEHAVIOR_56,
    CLIP_BEHAVIOR_57,
    CLIP_BEHAVIOR_58,
    CLIP_BEHAVIOR_59,
    CLIP_BEHAVIOR_60,
    CLIP_BEHAVIOR_61,
    CLIP_BEHAVIOR_62,
    CLIP_BEHAVIOR_63,

    CLIP_BEHAVIOR_WATER,

    CLIP_BEHAVIOR_65,
    CLIP_BEHAVIOR_66,
    CLIP_BEHAVIOR_67,
    CLIP_BEHAVIOR_68,
    CLIP_BEHAVIOR_69,
    CLIP_BEHAVIOR_70,
    CLIP_BEHAVIOR_71,
    CLIP_BEHAVIOR_72,
    CLIP_BEHAVIOR_73,
    CLIP_BEHAVIOR_74,
    CLIP_BEHAVIOR_75,
    CLIP_BEHAVIOR_76,
    CLIP_BEHAVIOR_77,
    CLIP_BEHAVIOR_78,
    CLIP_BEHAVIOR_79,

    CLIP_BEHAVIOR_WET_GROUND,
    CLIP_BEHAVIOR_DUSTY_GROUND,
    CLIP_BEHAVIOR_82,
    CLIP_BEHAVIOR_BUBBLY_GROUND,
    CLIP_BEHAVIOR_VERY_DUSTY_GROUND,

    CLIP_BEHAVIOR_85,
    CLIP_BEHAVIOR_86,
    CLIP_BEHAVIOR_87,
    CLIP_BEHAVIOR_88,
    CLIP_BEHAVIOR_89,
    CLIP_BEHAVIOR_90,
    CLIP_BEHAVIOR_91,
    CLIP_BEHAVIOR_92,
    CLIP_BEHAVIOR_93,
    CLIP_BEHAVIOR_94,
    CLIP_BEHAVIOR_95,
    CLIP_BEHAVIOR_96,
    CLIP_BEHAVIOR_97,
    CLIP_BEHAVIOR_98,
    CLIP_BEHAVIOR_99,
    CLIP_BEHAVIOR_100,
    CLIP_BEHAVIOR_101,
    CLIP_BEHAVIOR_102,
    CLIP_BEHAVIOR_103,
    CLIP_BEHAVIOR_104,
    CLIP_BEHAVIOR_105,
    CLIP_BEHAVIOR_106,
    CLIP_BEHAVIOR_107,
    CLIP_BEHAVIOR_108,
    CLIP_BEHAVIOR_109,
    CLIP_BEHAVIOR_110,
    CLIP_BEHAVIOR_111,
    CLIP_BEHAVIOR_112,
    CLIP_BEHAVIOR_113,
    CLIP_BEHAVIOR_114,
    CLIP_BEHAVIOR_115,
    CLIP_BEHAVIOR_116,
    CLIP_BEHAVIOR_117,
    CLIP_BEHAVIOR_118,
    CLIP_BEHAVIOR_119,
    CLIP_BEHAVIOR_120,
    CLIP_BEHAVIOR_121,
    CLIP_BEHAVIOR_122,
    CLIP_BEHAVIOR_123,
    CLIP_BEHAVIOR_124,
    CLIP_BEHAVIOR_125,
    CLIP_BEHAVIOR_126,

    CLIP_BEHAVIOR_GRAY_DOOR,
    CLIP_BEHAVIOR_WHITE_DOOR_SLOT_1,
    CLIP_BEHAVIOR_WHITE_DOOR_SLOT_2,
    CLIP_BEHAVIOR_WHITE_DOOR_SLOT_3,
    CLIP_BEHAVIOR_WHITE_DOOR_SLOT_4,
    CLIP_BEHAVIOR_WHITE_DOOR_SLOT_5,
    CLIP_BEHAVIOR_WHITE_DOOR_SLOT_6,
    CLIP_BEHAVIOR_BLUE_DOOR_SLOT_1,
    CLIP_BEHAVIOR_BLUE_DOOR_SLOT_2,
    CLIP_BEHAVIOR_BLUE_DOOR_SLOT_3,
    CLIP_BEHAVIOR_BLUE_DOOR_SLOT_4,
    CLIP_BEHAVIOR_BLUE_DOOR_SLOT_5,
    CLIP_BEHAVIOR_BLUE_DOOR_SLOT_6,
    CLIP_BEHAVIOR_GREEN_DOOR_SLOT_1,
    CLIP_BEHAVIOR_GREEN_DOOR_SLOT_2,
    CLIP_BEHAVIOR_GREEN_DOOR_SLOT_3,
    CLIP_BEHAVIOR_GREEN_DOOR_SLOT_4,
    CLIP_BEHAVIOR_GREEN_DOOR_SLOT_5,
    CLIP_BEHAVIOR_GREEN_DOOR_SLOT_6,
    CLIP_BEHAVIOR_YELLOW_DOOR_SLOT_1,
    CLIP_BEHAVIOR_YELLOW_DOOR_SLOT_2,
    CLIP_BEHAVIOR_YELLOW_DOOR_SLOT_3,
    CLIP_BEHAVIOR_YELLOW_DOOR_SLOT_4,
    CLIP_BEHAVIOR_YELLOW_DOOR_SLOT_5,
    CLIP_BEHAVIOR_YELLOW_DOOR_SLOT_6,
    CLIP_BEHAVIOR_RED_DOOR_SLOT_1,
    CLIP_BEHAVIOR_RED_DOOR_SLOT_2,
    CLIP_BEHAVIOR_RED_DOOR_SLOT_3,
    CLIP_BEHAVIOR_RED_DOOR_SLOT_4,
    CLIP_BEHAVIOR_RED_DOOR_SLOT_5,
    CLIP_BEHAVIOR_RED_DOOR_SLOT_6,

    CLIP_BEHAVIOR_END
};


#define CLIPDATA_TILEMAP_FLAG 0x8000

#endif /* CLIPDATA_CONSTANTS_H */
