#ifndef CONNECTION_CONSTANTS_H
#define CONNECTION_CONSTANTS_H

enum Area {
    AREA_MAIN_DECK,
    AREA_SECTOR_1,
    AREA_SECTOR_2,
    AREA_SECTOR_3,
    AREA_SECTOR_4,
    AREA_SECTOR_5,
    AREA_SECTOR_6,

    AREA_NORMAL_END = AREA_SECTOR_6,

    AREA_DEBUG_1,
    AREA_DEBUG_2,
    AREA_DEBUG_3,

    AREA_END,
};

enum NavigationRoom {
    NAV_ROOM_MAIN_DECK_ROOM_0,
    NAV_ROOM_MAIN_DECK_ROOM_16,
    NAV_ROOM_MAIN_DECK_ROOM_9,
    NAV_ROOM_MAIN_DECK_ROOM_32,
    NAV_ROOM_SECTOR_1_ROOM_2,
    NAV_ROOM_SECTOR_2_ROOM_2,
    NAV_ROOM_SECTOR_3_ROOM_2,
    NAV_ROOM_SECTOR_4_ROOM_2,
    NAV_ROOM_SECTOR_5_ROOM_2,
    NAV_ROOM_SECTOR_6_ROOM_2,
    NAV_ROOM_MAIN_DECK_ROOM_56,
    NAV_ROOM_MAIN_DECK_ROOM_66,
};

enum DoorType {
    DOOR_TYPE_NONE,
    DOOR_TYPE_AREA_CONNECTION,
    DOOR_TYPE_NO_HATCH,
    DOOR_TYPE_OPEN_HATCH,
    DOOR_TYPE_HATCH_CAN_LOCK,

    DOOR_TYPE_END,

    DOOR_TYPE_NO_FLAGS = 0xF,

    DOOR_TYPE_LOAD_EVENT_BASED_ROOM = (1 << 5),
    DOOR_TYPE_DISPLAY_LOCATION_NAME = (1 << 6),
};

#endif /* CONNECTION_CONSTANTS_H */
