#ifndef PARTICLE_CONSTANTS_H
#define PARTICLE_CONSTANTS_H

enum ParticleId {
    PE_NONE,
    PE_BOMB,
    PE_FLARE_HIT,
    PE_NORMAL_BEAM_HIT,
    PE_CHARGE_BEAM_HIT,
    PE_WIDE_BEAM_HIT,
    PE_PLASMA_BEAM_HIT,
    PE_INVINCIBLE_HIT,
    PE_MISSILE_EXPLOSION,
    PE_SUPER_MISSILE_EXPLOSION,
    PE_ICE_MISSILE_EXPLOSION,
    PE_DIFFUSION_MISSILE_EXPLOSION,
    PE_CHARGED_DIFFUSION_MISSILE_EXPLOSION,
    PE_0xD,
    PE_ICE_BEAM_TRAIL,
    PE_CHARGED_NORMAL_BEAM_TRAIL,
    PE_CHARGED_CHARGE_BEAM_TRAIL,
    PE_CHARGED_WIDE_BEAM_TRAIL,
    PE_CHARGED_PLASMA_BEAM_TRAIL,
    PE_CHARGED_WAVE_BEAM_TRAIL,
    PE_CHARGED_ICE_BEAM_TRAIL,
    PE_MISSILE_TRAIL,
    PE_SUPER_MISSILE_TRAIL,
    PE_ICE_MISSILE_TRAIL,
    PE_DIFFUSION_MISSILE_TRAIL,
    PE_CHARGED_DIFFUSION_MISSILE_TRAIL,
    PE_ABSORB_HEALTH_X,
    PE_ABSORB_MISSILE_X,
    PE_ABSORB_RED_X,
    PE_ABSORB_CORE_X,
    PE_ABSORB_ICE_X_PRE_VARIA,
    PE_ICE_X_TRAIL,
    PE_DIFFUSION_PARTICLES,
    PE_0x21,
    PE_0x22,
    PE_0x23,
    PE_0x24,
    PE_0x25,
    PE_0x26,
    PE_HEAVY_DUST_1,
    PE_HEAVY_DUST_2,
    PE_DUST_1,
    PE_DUST_2,
    PE_FIRE_BEAM,
    PE_ABSORBING_SUIT,
    PE_EXPLOSION_SMOKE,
    PE_TAIL_EXPLOSION_SMOKE,
    PE_0x2F,
    PE_0x30,
    PE_SMOKE,
    PE_0x32,
    PE_0x33,
    PE_TAIL_EXPLOSION,
    PE_0x35,
    PE_ENTER_OR_EXIT_WATER,
    PE_ENTER_OR_EXIT_WATER_BIG,
    PE_SPRITE_ENTER_OR_EXIT_WATER,
    PE_0x39,
    PE_0x3A,
    PE_OUTWARD_ICE_EXPLOSION,
    PE_OUTWARD_SMOKE,
    PE_SCREW_ATTACK_KILLED,
    PE_SPEEDBOOSTER_KILLED,
    PE_SHINESPARK_KILLED,
    PE_SUDO_SCREW_KILLED,
    PE_GETTING_SUIT_BEAMS,
    PE_GETTING_SUIT,
    PE_CHARGING_BEAM,
    PE_CHARGING_MISSILES,
    PE_0x45,
    PE_ESCAPE,

    PE_END
};

#define PARTICLE_STATUS_NONE               0
#define PARTICLE_STATUS_EXISTS             (1 << 0)
#define PARTICLE_STATUS_ONSCREEN           (1 << 1)
#define PARTICLE_STATUS_HIGH_OAM_PRIORITY          (1 << 2)
#define PARTICLE_STATUS_NOT_DRAWN          (1 << 3)
#define PARTICLE_STATUS_LIVE_OFF_SCREEN    (1 << 4)
#define PARTICLE_STATUS_LOW_BG_PRIORITY       (1 << 5)
#define PARTICLE_STATUS_ABSOLUTE_POSITION  (1 << 6)

#endif /* PARTICLE_CONSTANTS_H */
