#ifndef ARACHNUS_AI_H
#define ARACHNUS_AI_H

#include "types.h"

#define ARACHNUS_POSE_WALKING_INIT 1
#define ARACHNUS_POSE_WALKING 2
#define ARACHNUS_POSE_IDLE_INIT 7
#define ARACHNUS_POSE_IDLE 8
#define ARACHNUS_POSE_TURNING_INIT 3
#define ARACHNUS_POSE_TURNING 4
#define ARACHNUS_POSE_SLASHING 0x38
#define ARACHNUS_POSE_ROLLING 0x3a
#define ARACHNUS_POSE_BONKING 0x3c
#define ARACHNUS_POSE_SCREAMING 0x3e
#define ARACHNUS_POSE_SHOOTING_FIRE 0x40
#define ARACHNUS_POSE_DYING 0x42

#endif /* ARACHNUS_AI_H */
