#include "sprites_AI/target.h"
#include "sprites_AI/unused_sprites.h"
#include "sprites_AI/arachnus.h"
#include "sprites_AI/bubbles.h"
#include "sprites_AI/serris.h"
#include "sprites_AI/elevator_pad.h"

#include "data/sprites/target.h"
#include "data/sprites/arachnus.h"
#include "data/sprites/serris.h"
#include "data/sprites/elevator_pad.h"
