#ifndef SAMUS_H
#define SAMUS_H

#include "types.h"

void SamusCopyData(void);
s16 SamusChangeVelocityOnSlope(void);
void SamusSetPalette(const u16* src, s32 offset, s32 length, u32 isSax);
void SamusUpdatePhysics(void);
void SamusUpdateCollisionData(void);
void SamusCallUpdateGraphics(void);
void SamusCallCheckPlayLowHealthSound(void);
void SamusCheckUpdateArmCannonOffset(void);
void SamusBombBounce(u8 forcedMovement);
void SamusCheckSetNewEnvironmentEffect(u32 offset, u32 request);
void SamusUpdateEnvironmentEffect(void);
void SamusAimCannonStanding(void);
void SamusAimCannonMidAir(void);
void SamusAimCannonRunning(void);
void SamusAimCannonHorizontalLadder(void);
u8 SamusCheckShooting(void);
void SamusCheckNewProjectile(void);
u32 SamusCheckStandingOnDropThroughClipdata(void);
u32 SamusSetForcedMovementForJumpingOrDropping(void);
void SamusUpdateHighlightedWeaponsAndCharge(void);
void SamusSetSpinningPose(void);
void SamusApplyXAcceleration(s16 acceleration, s16 maxVelocity);
u32 SamusHazardDamage(void);
u32 SamusUpdate(void);
u8 SamusInactivity(void);
u8 SamusStanding(void);
u8 SamusStandingGfx(void);
u8 SamusTurningAround(void);
u8 SamusTurningAroundGfx(void);
u8 SamusShootingGfx(void);
u8 SamusRunning(void);
u8 SamusRunningGfx(void);
u8 SamusMidAir(void);
u8 SamusMidAirGfx(void);
u8 SamusTurningAroundMidAir(void);
u8 SamusTurningAroundMidAirGfx(void);
u8 SamusLandingGfx(void);
u8 SamusCrouching(void);
u8 SamusTurningAroundAndCrouching(void);
u8 SamusTurningAroundAndCrouchingGfx(void);
u8 SamusShootingAndCrouching(void);
u8 SamusShootingAndCrouchingGfx(void);
u8 SamusStartingASpinJumpGfx(void);
u8 SamusSpinning(void);
u8 SamusSpinningGfx(void);
u8 SamusMorphing(void);
u8 SamusMorphingGfx(void);
u8 SamusMorphBall(void);
u8 SamusMorphBallGfx(void);
u8 SamusRolling(void);
u8 SamusUnmorphing(void);
u8 SamusUnmorphingGfx(void);
u8 SamusMorphBallMidAir(void);
u8 SamusGettingHurtGfx(void);
u8 SamusGettingKnockedBackGfx(void);
u8 SamusStartingWallJumpGfx(void);
u8 SamusWallJumping(void);
u8 SamusUsingAnElevator(void);
u8 SamusUsingAnElevatorGfx(void);
u8 SamusHangingOnLedge(void);
u8 SamusHangingOnLedgeGfx(void);
u8 SamusPullingYourselfUpFromHanging(void);
u8 SamusPullingYourselfUpFromHangingGfx(void);
u8 SamusPullingYourselfForwardFromHanging(void);
u8 SamusPullingYourselfForwardFromHangingGfx(void);
u8 SamusPullingYourselfIntoMorphballTunnel(void);
u8 SamusPullingYourselfIntoMorphballTunnelGfx(void);
u8 SamusPullingYourselfDownToStartHanging_Unused(void);
u8 SamusPullingYourselfDownToStartHanging_UnusedGfx(void);
u8 SamusSpaceJumpingGfx(void);
u8 SamusScrewAttackingGfx(void);
u8 SamusSkidding(void);
u8 SamusOnSavePadGfx(void);
u8 SamusTurningAroundToRechargeOrUnlockSecurityGfx(void);
u8 SamusDelayBeforeShinesparkingGfx(void);
u8 SamusShinesparking(void);
u8 SamusShinesparkingGfx(void);
u8 SamusDelayAfterShinesparkingGfx(void);
u8 SamusHangingFromVerticalLadder(void);
u8 SamusHangingFromVerticalLadderGfx(void);
u8 SamusStartingToHoldYourArmCannonOutOnAVerticalLadder(void);
u8 SamusStartingToHoldYourArmCannonOutOnAVerticalLadderGfx(void);
u8 SamusHoldingYourArmCannonOutOnAVerticalLadder(void);
u8 SamusShootingOnVerticalLadderGfx(void);
u8 SamusStartingToPutAwayYourArmCannonOnVerticalLadder(void);
u8 SamusStartingToPutAwayYourArmCannonOnVerticalLadderGfx(void);
u8 SamusHangingOnHorizontalLadder(void);
u8 SamusMovingOnHorizontalLadder(void);
u8 SamusMovingOnHorizontalLadderGfx(void);
u8 SamusTurningAroundOnHorizontalLadder(void);
u8 SamusTurningAroundOnHorizontalLadderGfx(void);
u8 SamusDelayAfterShootingOnHorizontalLadder(void);
u8 SamusShootingOnHorizontalLadderGfx(void);
u8 SamusFrozenGfx(void);
u8 SamusFrozenInMorphBallGfx(void);
u8 SamusUnlockingSecurityGfx(void);
u8 SamusSavingGfx(void);
u8 SavingOnNavigationPadGfx(void);
u8 SamusDownloadingAbilityGfx(void);
u8 SamusBeingRechargedGfx(void);
u8 SamusFacingForeground(void);
u8 SamusFacingForegroundGfx(void);
u8 SamusUnlockingHabitationsDeckGfx(void);
u8 SamusLoadingSave(void);
u8 SamusLoadingSaveGfx(void);
u8 SamusDying(void);
u8 SamusDyingGfx(void);
u8 SamusHitByOmagaMetroid(void);
u8 SamusHitByOmegaMetroidGfx(void);
u8 SamusGrabbedByYakuza(void);
void SamusSetPose(u8 pose);
void SamusSetMidAirPose(void);
void SamusSetLandingPose(void);
void SamusSetFreezedPose(void);
void SamusSetHurtPose(void);
void SamusSetKnockbackPose(void);
void unk_99a0(void);
void unk_99d8(void);
void SamusCheckCarryFromCopy(void);
void SamusUpdateVelocityPosition(void);
void SamusCheckScrewSpeedboosterAffectingEnvironment(void);
void SamusCheckCollisions(void);
u8 SamusCheckCollisionAtPosition(u16 xPosition, u16 yPosition, u16* pNextY, u16* pNextX, u16* param_5);
u8 unk_a670(u8 collisionType, u16* pNextX, s16 hitbox);
u8 unk_a7b8(u8 param_1, s16 hitbox, u8 param_3);
u8 unk_a8fc(u8 collisionType, u16 yPosition, u16* param_3);
u8 SamusCheckWalkingSidesCollision(void);
u8 SamusCheckStandingOnGroundCollision(void);
u8 SamusCheckLandingCollision(void);
u8 SamusCheckJumpingCollision(void);
u8 unk_b3c8(void);
void SamusUpdateGraphics(u8 facingLeft);
void SamusCheckPlayLowHealthSound(void);
void SamusUpdateDrawDistanceAndStandingStatus(void);
void SamusUpdateArmCannonOffset(u8 facingLeft);
void SamusInit(void);
void SamusDraw(void);

#endif /* SAMUS_H */
