#ifndef DEBUG_MENU_CONSTANTS_H
#define DEBUG_MENU_CONSTANTS_H

#include "types.h"

#define DEBUG_MENU_TILE_SIZE (QUARTER_BLOCK_SIZE / 2)

enum DebugMenuSection {
    DEBUG_SECTION_BEAM,
    DEBUG_SECTION_MISSILE,
    DEBUG_SECTION_BOMB,
    DEBUG_SECTION_SUIT,
    DEBUG_SECTION_MISC,
    DEBUG_SECTION_ENERGY_CURRENT,
    DEBUG_SECTION_ENERGY_MAX,
    DEBUG_SECTION_SUPPLY,
    DEBUG_SECTION_MISSILE_CURRENT,
    DEBUG_SECTION_MISSILE_MAX,
    DEBUG_SECTION_POWER_BOMB_CURRENT,
    DEBUG_SECTION_POWER_BOMB_MAX,
    DEBUG_SECTION_ABILITY_COUNT,
    DEBUG_SECTION_SECURITY,
    DEBUG_SECTION_MAP,
    DEBUG_SECTION_EVENT,
    DEBUG_SECTION_SUB_EVENT,
    DEBUG_SECTION_IN_GAME_TIME,
    DEBUG_SECTION_QUICK_SAVE,

    DEBUG_SECTION_END,

    DEBUG_SECTION_ALL = UCHAR_MAX
};

enum DebugMenuEditFlag {
    DEBUG_EDIT_NONE,
    DEBUG_EDIT_REDRAW_SECTION,
    DEBUG_EDIT_REDRAW_NUMBERED_SECTION,
    DEBUG_EDIT_REDRAW_ALL,
};

enum DebugMenuAmmoType {
    DEBUG_AMMO_TYPE_HEALTH,
    DEBUG_AMMO_TYPE_MISSILES,
    DEBUG_AMMO_TYPE_POWER_BOMBS,
};

#endif /* DEBUG_MENU_CONSTANTS_H */
