#ifndef PAUSE_SCREEN_CONSTANTS_H
#define PAUSE_SCREEN_CONSTANTS_H

#include "types.h"

enum SubArea {
    SUB_AREA_NONE,
    SUB_AREA_OPERATIONS_DECK,
    SUB_AREA_DOCKING_BAYS,
    SUB_AREA_HABITATION_DECK,
    SUB_AREA_MAIN_DECK,
    SUB_AREA_REACTOR_SILO,
    SUB_AREA_RESTRICTED_ZONE,
    SUB_AREA_SECTOR_1,
    SUB_AREA_SECTOR_2,
    SUB_AREA_SECTOR_3,
    SUB_AREA_SECTOR_4,
    SUB_AREA_SECTOR_5,
    SUB_AREA_SECTOR_6,

    SUB_AREA_END
};

#endif /* PAUSE_SCREEN_CONSTANTS_H */
