#ifndef TITLE_SCREEN_CONSTANTS_H
#define TITLE_SCREEN_CONSTANTS_H

#include "types.h"

enum TitleScreenSection {
    TITLE_SCREEN_SECTION_NONE,
    TITLE_SCREEN_SECTION_COPYRIGHT,
    TITLE_SCREEN_SECTION_PRESS_START,
    TITLE_SCREEN_SECTION_LANGUAGE,
    TITLE_SCREEN_SECTION_4,
    TITLE_SCREEN_SECTION_GALLERY,

    TITLE_SCREEN_SECTION_END
};

#endif /* TITLE_SCREEN_CONSTANTS_H */
